// <auto-generated />
using System;
using CouponHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CouponHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CouponHub.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("CouponHub.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CouponCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("coupon_code");

                    b.Property<string>("CouponSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coupon_source");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discount_type");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("discount_value");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MaximumDiscount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("maximum_discount");

                    b.Property<decimal?>("MinimumOrderAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("minimum_order_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.Property<Guid?>("OwnerId").HasColumnType("uuid").HasColumnName("owner_id");
                    b.HasIndex("BrandId", "CouponCode").IsUnique().HasFilter("owner_id IS NULL");
                    b.HasIndex("OwnerId", "BrandId", "CouponCode").IsUnique().HasFilter("owner_id IS NOT NULL");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("CouponHub.Domain.Entities.Coupon", b =>
                {
                    b.HasOne("CouponHub.Domain.Entities.Brand", "Brand")
                        .WithMany("Coupons")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CouponHub.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.Account", b => {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Email").IsRequired().HasMaxLength(254).HasColumnType("character varying(254)");
                b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<bool>("IsAdmin").HasColumnType("boolean");
                b.Property<string[]>("Categories").IsRequired().HasColumnType("text[]");
                b.HasKey("Id"); b.HasIndex("Email").IsUnique(); b.ToTable("accounts");
            });
            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.Session", b => {
                b.Property<string>("TokenHash").HasMaxLength(64).HasColumnType("character varying(64)");
                b.Property<Guid>("AccountId").HasColumnType("uuid");
                b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.HasKey("TokenHash"); b.HasIndex("AccountId"); b.HasIndex("ExpiresAt"); b.ToTable("sessions");
            });
            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.SavedCoupon", b => {
                b.Property<Guid>("AccountId").HasColumnType("uuid");
                b.Property<Guid>("CouponId").HasColumnType("uuid");
                b.Property<DateTime>("SavedAt").HasColumnType("timestamp with time zone");
                b.HasKey("AccountId", "CouponId"); b.HasIndex("CouponId"); b.ToTable("saved_coupons");
            });
            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.CouponEvent", b => {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("AccountId").HasColumnType("uuid");
                b.Property<Guid>("CouponId").HasColumnType("uuid");
                b.Property<string>("Kind").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.HasKey("Id"); b.HasIndex("AccountId", "CreatedAt"); b.HasIndex("CouponId"); b.ToTable("coupon_events");
            });
            modelBuilder.Entity("CouponHub.Domain.Entities.Coupon", b => {
                b.HasOne("CouponHub.Infrastructure.Personalization.Account", null).WithMany()
                    .HasForeignKey("OwnerId").OnDelete(DeleteBehavior.Cascade);
            });
            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.Session", b => {
                b.HasOne("CouponHub.Infrastructure.Personalization.Account", null).WithMany()
                    .HasForeignKey("AccountId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.SavedCoupon", b => {
                b.HasOne("CouponHub.Infrastructure.Personalization.Account", null).WithMany()
                    .HasForeignKey("AccountId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("CouponHub.Domain.Entities.Coupon", null).WithMany()
                    .HasForeignKey("CouponId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
            modelBuilder.Entity("CouponHub.Infrastructure.Personalization.CouponEvent", b => {
                b.HasOne("CouponHub.Infrastructure.Personalization.Account", null).WithMany()
                    .HasForeignKey("AccountId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("CouponHub.Domain.Entities.Coupon", null).WithMany()
                    .HasForeignKey("CouponId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
