<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CouponHub.Domain\CouponHub.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Services\" />
    <Folder Include="Brands\DTOs\" />
    <Folder Include="Brands\Queries\" />
    <Folder Include="Coupons\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
